### PR TITLE
fix: use static language list instead of l10nFactory for translation providers

### LINKED ISSUE #357: OldTranslationProvider returns empty/single language list when force_language is set
## Bug Description

When `force_language` is set in `config.php` (e.g., `'force_language' => 'tr'`), the `OldTranslationProvider::getAvailableLanguages()` method returns only the forced language instead of all languages that the AI model can translate between.

This causes the **translation language dropdowns to appear empty** (or with only 1 language) in any app that uses the legacy `ITranslationManager` API — most notably **Nextcloud Talk (spreed)**, where clicking "Translate" on a chat message shows no language options.

## Root Cause

`OldTranslationProvider::getAvailableLanguages()` uses `$this->l10nFactory->getLanguages()` to build the language pair list:

```php
$coreL = $this->l10nFactory->getLanguages();
$languages = array_merge($coreL['commonLanguages'], $coreL['otherLanguages']);
```

`IFactory::getLanguages()` returns **installed UI translation languages**, not all languages the AI can translate. When `force_language` restricts the server to a single locale, only that one language is returned → N×(N-1) = 0 language pairs.

The newer `TranslateProvider` (TaskProcessing API) has the same underlying issue — it also relies on `l10nFactory->getLanguages()` in `getInputShapeEnumValues()`, but this path is used by the Assistant app which may handle it differently.

## Steps to Reproduce

1. Set `'force_language' => 'tr'` in `config.php`
2. Enable `integration_openai` with a working API endpoint
3. Open Nextcloud Talk (spreed)
4. Click the "⋯" (more options) menu on a message → "Translate"
5. Source and target language dropdowns are empty

## Expected Behavior

The translation provider should list all languages that the AI model can translate between, regardless of the server's `force_language` setting. An AI translation provider's available languages are independent of the server's UI language configuration.

## Suggested Fix

Instead of relying on `l10nFactory->getLanguages()`, use a static/hardcoded list of common languages (similar to how the model already translates via free-text prompts and is not limited to installed locales). This list could be:
- A comprehensive set of ISO 639 languages
- Configurable via admin settings
- Or fetched from a standard language registry

This would also fix the same issue in `TranslateProvider::getInputShapeEnumValues()`.

## Environment

- Nextcloud: 33.0.2
- integration_openai: 4.3.1
- PHP: 8.4
- Talk (spreed): 23.0.3
- `force_language`: `tr`

### PR DESCRIPTION
**Pull request by bakiburakogun**
## Summary

When `force_language` is set in `config.php`, `l10nFactory->getLanguages()` returns only the forced language (or a very limited set), causing both `OldTranslationProvider` and `TranslateProvider` to offer an empty or single-language list to consumers like Spreed's message translation dialog.

AI translation services (OpenAI, LocalAI, etc.) can translate between any languages regardless of which Nextcloud UI languages are installed. The available translation language list should therefore not depend on `l10nFactory`.

## Changes

- **New `lib/Translation/LanguageList.php`**: A shared static helper class providing ~80 common ISO 639 languages with English names. Exposes `getLanguages()` (array of `['code' => ..., 'name' => ...]`) and `getLanguagesByCode()` (`code => name` map).
- **`OldTranslationProvider`**: `getAvailableLanguages()` and `getCoreLanguagesByCode()` now use `LanguageList` instead of `l10nFactory->getLanguages()`.
- **`TranslateProvider`**: `getInputShapeEnumValues()` and `getCoreLanguagesByCode()` now use `LanguageList` instead of `l10nFactory->getLanguages()`.

## How to reproduce

1. Set `'force_language' => 'tr'` (or any single language) in `config.php`
2. Open Spreed → select a message → click Translate
3. The source/target language dropdowns are empty or show only one language

With this fix, all ~80 common languages are always available.

Fixes #357

### CODE REVIEW

File: lib/Translation/LanguageList.php [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+ */
+class LanguageList {
+
+	/**
+	 * Returns a comprehensive list of common languages with English display names.
+	 *
+	 * @return array<array{code: string, name: string}>
+	 */
+	public static function getLanguages(): array {
+		return [
```
Comment (lukasdotcom) [inline lib/Translation/LanguageList.php]: The languages should be internationalized. I would just use the endonyms (https://en.wikipedia.org/wiki/Endonym_and_exonym) for them. Also could you merge it with the list in https://github.com/nextcloud/integration_openai/blob/main/lib/AppInfo/Application.php#L83 and use your getLanguages for where that constant is being used so there is only one list.

**Review by lukasdotcom — COMMENTED** [review]
Thanks. It looks good I have a little bit of feedback, and to fix the DCO check you need to sign your commits. The instructions for that are at https://github.com/nextcloud/integration_openai/pull/358/checks?check_run_id=70509628723

**Comment by lukasdotcom** [comment]
Hey @bakiburakogun, are you still interested in implementing the review changes yourself or do you want me to?

**Review by lukasdotcom — APPROVED** [review]

File: lib/AppInfo/Application.php [hunk 2]
```diff
@@ -80,7 +80,7 @@ class Application extends App implements IBootstrap {
...
...ارسی'], ['lv', 'Latviešu'], ['bn', 'বাংলা'], ['sr', 'Српски'], ['az', 'Azərbaycanca / آذربايجان'], ['sl', 'Slovenščina'], ['kn', 'ಕನ್ನಡ'], ['et', 'Eesti'], ['mk', 'Македонски'], ['br', 'Brezhoneg'], ['eu', 'Euskara'], ['is', 'Íslenska'], ['hy', 'Հայերեն'], ['ne', 'नेपाली'], ['mn', 'Монгол'], ['bs', 'Bosanski'], ['kk', 'Қазақша'], ['sq', 'Shqip'], ['sw', 'Kiswahili'], ['gl', 'Galego'], ['mr', 'मराठी'], ['pa', 'ਪੰਜਾਬੀ / पंजाबी / پنجابي'], ['si', 'සිංහල'], ['km', 'ភាសាខ្មែរ'], ['sn', 'chiShona'], ['yo', 'Yorùbá'], ['so', 'Soomaaliga'], ['af', 'Afrikaans'], ['oc', 'Occitan'], ['ka', 'ქართული'], ['be', 'Беларуская'], ['tg', 'Тоҷикӣ'], ['sd', 'सिनधि'], ['gu', 'ગુજરાતી'], ['am', 'አማርኛ'], ['yi', 'ייִדיש'], ['lo', 'ລາວ / Pha xa lao'], ['uz', 'Ўзбек'], ['fo', 'Føroyskt'], ['ht', 'Krèyol ayisyen'], ['ps', 'پښتو'], ['tk', 'Туркмен / تركمن'], ['nn', 'Norsk (nynorsk)'], ['mt', 'bil-Malti'], ['sa', 'संस्कृतम्'], ['lb', 'Lëtzebuergesch'], ['my', 'Myanmasa'], ['bo', 'བོད་ཡིག / Bod skad'], ['tl', 'Tagalog'], ['mg', 'Malagasy'], ['as', 'অসমীয়া'], ['tt', 'Tatarça'], ['haw', 'ʻŌlelo Hawaiʻi'], ['ln', 'Lingála'], ['ha', 'هَوُسَ'], ['ba', 'Башҡорт'], ['jw', 'ꦧꦱꦗꦮ'], ['su', 'Basa Sunda'], ['yue', '粤语']];
```
Comment (marcelklehr) [inline lib/AppInfo/Application.php:83]: While the original L10N Service uses endonyms, I think it makes more sense to use exonyms here and have them translatable into the user's selected language, as the user may not speak the language(s) well enough to know the proper endonym.

Comment (marcelklehr) [reply lib/AppInfo/Application.php:83]: (see https://github.com/nextcloud/integration_openai/issues/269 )
